### ISSUE TITLE
Add a gitignore.

### ISSUE THREAD

**Issue by davidgarland** [FoxCA/foxos#2]
You guys have non-portable `.o` files in `/src/arch/x86_64/kernel/`.

You can filter these out of your project by making a `.gitignore` file in the top-level directory for `foxos` with the file extensions you want to omit. Here's an example one I might recommend to get started:

```
*.o
*.out
*.gch
*.a
*.so
*.iso
*~
```

This will prevent such slip-ups in the future even if you forget to run `make clean` or similar.

**Comment by jdonszelmann** [comment]
Thanks for the suggestion! You're right. I'll change it :)

**Comment by SarahIsWeird** [comment]
Fixed (Jona added .build/ and I added *.o) Should be done.
